export function LiabilityWaiverConsentDocument() {
  return (
    <div className="space-y-6 text-base leading-relaxed text-[var(--color-charcoal)]">
      <p>
        This Liability Waiver & Release of Claims (“Waiver”) is a legally binding agreement between
        the User (“User,” “you,” “your”) and NxtStps Technologies LLC and its parent, subsidiaries,
        affiliates, officers, directors, employees, contractors, agents, successors, and assigns
        (collectively, “NxtStps,” “Company,” “we,” or “us”).
      </p>
      <p>
        By accessing or using the NxtStps platform (“Platform”), User knowingly and voluntarily
        agrees to the terms below.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 1 – ACKNOWLEDGMENT OF NON-PROFESSIONAL STATUS
      </h2>
      <h3 className="text-base font-medium text-[var(--color-charcoal)]">
        1.1 No Legal Advice or Legal Representation
      </h3>
      <p>
        User acknowledges and agrees that NxtStps: (a) is not a law firm; (b) does not provide legal
        advice, legal interpretation, or legal advocacy; (c) does not review submissions for legal
        sufficiency; (d) does not apply law to User-specific facts; and (e) does not act as a
        representative, advocate, or agent in any legal or administrative matter.
      </p>
      <h3 className="text-base font-medium text-[var(--color-charcoal)]">
        1.2 No Medical, Clinical, or Therapeutic Services
      </h3>
      <p>
        User acknowledges that NxtStps is not a provider of medical, psychological,
        crisis-intervention, trauma therapy, or clinical services.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 2 – ASSUMPTION OF ALL RISKS ASSOCIATED WITH PLATFORM USE
      </h2>
      <p>
        User expressly understands, acknowledges, and agrees that use of the Platform involves
        inherent risks, including but not limited to: submission of incomplete or inaccurate
        information; denial, delay, or rejection of applications; adverse outcomes in benefit or
        compensation claims; missed deadlines or procedural deficiencies; emotional distress
        associated with revisiting traumatic events; document formatting or technical errors;
        misinterpretation of third-party program requirements; incorrect or incomplete AI-generated
        suggestions; data entry, upload, or transmission errors. User voluntarily assumes all such
        risks, whether known or unknown.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 3 – RELEASE OF CLAIMS AGAINST NXTSTPS
      </h2>
      <p>
        In consideration for accessing and using the Platform, User hereby fully and irrevocably
        releases NxtStps from any and all claims, liabilities, damages, losses, demands, causes of
        action, and legal proceedings—whether known or unknown, suspected or unsuspected, direct or
        indirect—arising out of or connected to Platform use.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 4 – USER’S DUTY TO VERIFY ALL INFORMATION
      </h2>
      <p>
        User acknowledges and agrees that they must independently verify all information before
        signing, certifying, submitting, or otherwise relying on documents prepared through or
        generated by the Platform.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 5 – NO WARRANTIES; DISCLAIMERS
      </h2>
      <p>
        The Platform is provided strictly “as is” and “as available,” without warranties of any kind.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 6 – LIMITATION OF LIABILITY
      </h2>
      <p className="font-semibold text-[var(--color-navy)]">
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, USER AGREES THAT NXTSTPS SHALL NOT BE LIABLE FOR
        INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES; TOTAL
        LIABILITY SHALL NOT EXCEED ONE HUNDRED DOLLARS ($100) OR THE AMOUNT PAID BY USER IN THE
        PRECEDING TWELVE (12) MONTHS, WHICHEVER IS LESS.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 7 – INDEMNIFICATION
      </h2>
      <p>
        User agrees to indemnify, defend, and hold harmless NxtStps from all claims, liabilities,
        damages, and expenses—including attorney’s fees—arising out of User’s reliance on Platform
        outputs and related conduct.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 8 – KNOWING AND VOLUNTARY AGREEMENT
      </h2>
      <p>
        User acknowledges that this Waiver includes material provisions that substantially limit
        User’s rights and NxtStps’ liability. User affirms that they have read, understood, and
        voluntarily agree to this Waiver.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">
        SECTION 9 – GOVERNING LAW; ARBITRATION; CLASS ACTION WAIVER
      </h2>
      <p>
        This Waiver shall be governed by the laws of the State of Illinois. Disputes shall be
        resolved through binding arbitration in Chicago, Illinois, as described in the Terms of Use,
        where applicable.
      </p>

      <h2 className="text-lg font-semibold text-[var(--color-navy)] pt-2">SECTION 10 – SEVERABILITY</h2>
      <p>
        If any provision of this Waiver is held unenforceable, the remaining provisions shall remain
        enforceable to the fullest extent permitted by law.
      </p>

      <p className="font-medium text-[var(--color-navy)] pt-4">
        USER ACKNOWLEDGMENT: By accepting in the consent flow, the User acknowledges that they have
        read, understood, and voluntarily consent to be bound by this Liability Waiver & Release of
        Claims.
      </p>

      <p className="text-sm text-[var(--color-muted)]">
        Version referenced at acceptance: January 2025 baseline. If you’re in immediate danger, call
        911. If you need support now, call or text 988.
      </p>
    </div>
  );
}
