import Link from "next/link";

export const metadata = {
  title: "Liability Waiver & Release of Claims · NxtStps",
};

export default function WaiverPage() {
  return (
    <main className="min-h-screen bg-[#020b16] text-slate-50 px-6 py-10">
      <div className="max-w-3xl mx-auto space-y-8">
        <div className="flex flex-wrap gap-4 text-sm text-slate-400">
          <Link href="/" className="hover:text-slate-200">← Home</Link>
          <Link href="/terms" className="hover:text-slate-200">Terms</Link>
          <Link href="/privacy" className="hover:text-slate-200">Privacy</Link>
        </div>
        <header className="space-y-2">
          <p className="text-[11px] uppercase tracking-[0.25em] text-slate-400">
            Legal
          </p>
          <h1 className="text-3xl font-bold">
            NXTSTPS – LIABILITY WAIVER & RELEASE OF CLAIMS
          </h1>
          <p className="text-sm text-slate-300">
            Effective Date: January 2025 · Last Updated: January 2025
          </p>
        </header>

        <section className="prose prose-invert prose-sm max-w-none space-y-6 text-slate-200">
          <p>
            This Liability Waiver & Release of Claims (“Waiver”) is a legally
            binding agreement between the User (“User,” “you,” “your”) and
            NxtStps Technologies LLC and its parent, subsidiaries, affiliates,
            officers, directors, employees, contractors, agents, successors,
            and assigns (collectively, “NxtStps,” “Company,” “we,” or “us”).
          </p>
          <p>
            By accessing or using the NxtStps platform (“Platform”), User
            knowingly and voluntarily agrees to the terms below.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 1 – ACKNOWLEDGMENT OF NON-PROFESSIONAL STATUS
          </h2>
          <h3 className="text-base font-medium text-slate-200">1.1 No Legal Advice or Legal Representation</h3>
          <p>
            User acknowledges and agrees that NxtStps: (a) is not a law firm;
            (b) does not provide legal advice, legal interpretation, or legal
            advocacy; (c) does not review submissions for legal sufficiency;
            (d) does not apply law to User-specific facts; and (e) does not act
            as a representative, advocate, or agent in any legal or
            administrative matter.
          </p>
          <h3 className="text-base font-medium text-slate-200">1.2 No Medical, Clinical, or Therapeutic Services</h3>
          <p>
            User acknowledges that NxtStps is not a provider of medical,
            psychological, crisis-intervention, trauma therapy, or clinical
            services.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 2 – ASSUMPTION OF ALL RISKS ASSOCIATED WITH PLATFORM USE
          </h2>
          <p>
            User expressly understands, acknowledges, and agrees that use of
            the Platform involves inherent risks, including but not limited
            to: submission of incomplete or inaccurate information; denial,
            delay, or rejection of applications; adverse outcomes in benefit or
            compensation claims; missed deadlines or procedural deficiencies;
            emotional distress associated with revisiting traumatic events;
            document formatting or technical errors; misinterpretation of
            third-party program requirements; incorrect or incomplete
            AI-generated suggestions; data entry, upload, or transmission
            errors. User voluntarily assumes all such risks, whether known or
            unknown.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 3 – RELEASE OF CLAIMS AGAINST NXTSTPS
          </h2>
          <p>
            In consideration for accessing and using the Platform, User hereby
            fully and irrevocably releases NxtStps from any and all claims,
            liabilities, damages, losses, demands, causes of action, and legal
            proceedings—whether known or unknown, suspected or unsuspected,
            direct or indirect—arising out of or connected to Platform use.
            This release includes claims based on: negligence; UPL allegations;
            misrepresentation or reliance; product liability; emotional
            distress; failure to warn; and third-party agency decisions.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 4 – USER’S DUTY TO VERIFY ALL INFORMATION
          </h2>
          <p>
            User acknowledges and agrees that they must independently verify
            all information before signing, certifying, submitting, or
            otherwise relying on documents prepared through or generated by the
            Platform. User agrees that they, and they alone, are responsible
            for: the accuracy of submissions; the completeness of
            documentation; ensuring compliance with all program requirements;
            understanding eligibility criteria; meeting deadlines; and
            reviewing all final documents.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 5 – NO WARRANTIES; DISCLAIMERS
          </h2>
          <p>
            The Platform is provided strictly “as is” and “as available,”
            without warranties of any kind. NxtStps does not guarantee:
            accuracy of content; completeness of AI suggestions; eligibility
            outcomes; successful submission; or acceptance of any document by
            third parties.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 6 – LIMITATION OF LIABILITY
          </h2>
          <p className="font-semibold text-slate-100">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, USER AGREES THAT: NXTSTPS
            SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
            PUNITIVE, OR CONSEQUENTIAL DAMAGES; NXTSTPS SHALL NOT BE LIABLE FOR
            LOSS OF DATA, EMOTIONAL DISTRESS, LOST BENEFITS, LOST OPPORTUNITY,
            OR ANY FORM OF PERSONAL OR ECONOMIC LOSS; TOTAL LIABILITY OF
            NXTSTPS SHALL NOT EXCEED ONE HUNDRED DOLLARS ($100) OR THE AMOUNT
            PAID BY USER IN THE PRECEDING TWELVE (12) MONTHS, WHICHEVER IS LESS.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 7 – INDEMNIFICATION
          </h2>
          <p>
            User agrees to indemnify, defend, and hold harmless NxtStps from
            all claims, liabilities, damages, and expenses—including attorney’s
            fees—arising out of: User’s reliance on Platform outputs; User’s
            inaccurate or incomplete submissions; User’s misinterpretation of
            program requirements; User violations of law or confidentiality
            obligations; User’s use of the Platform in a manner inconsistent
            with this Waiver or the Terms of Use.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 8 – KNOWING AND VOLUNTARY AGREEMENT
          </h2>
          <p>
            User acknowledges that this Waiver includes material provisions
            that substantially limit User’s rights and NxtStps’ liability.
            User affirms that they have read, understood, and voluntarily
            agree to this Waiver without coercion or undue influence. User
            represents that they are mentally and legally capable of entering
            into this Waiver.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 9 – GOVERNING LAW; ARBITRATION; CLASS ACTION WAIVER
          </h2>
          <p>
            This Waiver shall be governed by the laws of the State of
            Illinois. All disputes arising from this Waiver shall be resolved
            exclusively through binding arbitration administered by the
            American Arbitration Association (AAA) in Chicago, Illinois. User
            waives any right to participate in a class, collective,
            consolidated, or representative action.
          </p>

          <h2 className="text-lg font-semibold text-slate-100 pt-4">
            SECTION 10 – SEVERABILITY
          </h2>
          <p>
            If any provision of this Waiver is held unenforceable, the
            remaining provisions shall remain enforceable to the fullest
            extent permitted by law.
          </p>

          <p className="font-medium text-slate-100 pt-6">
            USER ACKNOWLEDGMENT: By clicking “I Agree,” “Accept,” or using the
            Platform, the User acknowledges that they have read, understood,
            and voluntarily consent to be bound by this Liability Waiver &
            Release of Claims.
          </p>

          <p className="text-[11px] text-slate-400 pt-6">
            If you’re in immediate danger, call 911. If you need support now,
            call or text 988.
          </p>
        </section>
      </div>
    </main>
  );
}
