/**
 * Domain 7.3 — AI Ops release-gate suite.
 *
 * Covers: mode registry integrity, prompt registry coverage, tool allowlist
 * enforcement, Layer 1 mode constraint, Layer 4 disclaimer injection,
 * orchestrator shape + model routing.
 */

import { describe, it, expect } from "vitest";
import {
  AI_MODES,
  MODEL_ROUTING,
  allModes,
  executeToolCall,
  getModeConfig,
  getPrompt,
  isToolAllowed,
  orchestrate,
  runSafetyPipeline,
  type AIModeKey,
  type ModelInvoker,
} from "@/lib/server/aiOps";

describe("aiModeRegistry — integrity", () => {
  it("defines the 5 canonical modes", () => {
    const modes = allModes().sort();
    expect(modes).toEqual([
      "admin_evaluation",
      "applicant_guidance",
      "document_explanation",
      "intake_explanation",
      "provider_copilot",
    ]);
  });

  it("every mode has required fields", () => {
    for (const m of allModes()) {
      const c = getModeConfig(m);
      expect(typeof c.modelTier).toBe("string");
      expect(Array.isArray(c.allowedTools)).toBe(true);
      expect(c.maxTokens).toBeGreaterThan(0);
      expect(typeof c.systemPromptKey).toBe("string");
      expect(Array.isArray(c.allowedContextScopes)).toBe(true);
      expect(Array.isArray(c.forbiddenResponsePatterns)).toBe(true);
    }
  });

  it("every mode's systemPromptKey resolves to an active prompt", () => {
    for (const m of allModes()) {
      const key = getModeConfig(m).systemPromptKey;
      const prompt = getPrompt(key);
      expect(prompt.active).toBe(true);
      expect(prompt.systemPrompt.length).toBeGreaterThan(0);
    }
  });
});

describe("aiToolRuntime — allowlist", () => {
  it("isToolAllowed respects the mode's allowedTools", () => {
    expect(isToolAllowed("getCrisisResources", "applicant_guidance")).toBe(true);
    expect(isToolAllowed("createDraftNote", "applicant_guidance")).toBe(false);
    expect(isToolAllowed("createDraftNote", "provider_copilot")).toBe(true);
  });

  it("executeToolCall throws FORBIDDEN when tool is not in mode allowlist", async () => {
    await expect(
      executeToolCall("createDraftNote", {}, "applicant_guidance", {
        stateCode: "IL",
      }),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
  });

  it("executeToolCall runs an allowed tool and returns a log without params/results", async () => {
    // Use getFieldDefinition — pure stub, hermetic. getCrisisResources now
    // reaches the live knowledge catalog and is covered by KB tests instead.
    const res = await executeToolCall(
      "getFieldDefinition",
      { field_key: "victim.firstName" },
      "intake_explanation",
      {},
    );
    expect(res.log.tool_name).toBe("getFieldDefinition");
    expect(res.log.mode).toBe("intake_explanation");
    expect(res.log.ok).toBe(true);
    expect(typeof res.log.duration_ms).toBe("number");
    // The log intentionally contains NO parameter or result contents.
    const logKeys = Object.keys(res.log).sort();
    expect(logKeys).toEqual(["duration_ms", "mode", "ok", "tool_name"]);
  });
});

describe("aiSafetyPipeline — layers 1 and 4", () => {
  it("Layer 1: forbidden pattern in response triggers mode constraint", () => {
    const result = runSafetyPipeline(
      "I guarantee you will win your case.",
      "applicant_guidance",
    );
    expect(result.safe).toBe(false);
    expect(result.layersFailed.some((l) => l.startsWith("layer1:"))).toBe(true);
    // The response is replaced with the safe fallback.
    expect(result.response).not.toContain("guarantee");
  });

  it("Layer 4: disclaimer appended for applicant_guidance", () => {
    const result = runSafetyPipeline(
      "Here's a quick summary of your next step.",
      "applicant_guidance",
    );
    expect(result.safe).toBe(true);
    expect(result.disclaimerAdded).toBe(true);
    expect(result.response).toContain("not legal advice");
  });

  it("Layer 4: no disclaimer for intake_explanation (disclaimerKey null)", () => {
    const result = runSafetyPipeline(
      "This field asks for your current home address.",
      "intake_explanation",
    );
    expect(result.safe).toBe(true);
    expect(result.disclaimerAdded).toBe(false);
  });

  it("Layer 5: escalation detected in model output triggers safe fallback", () => {
    const result = runSafetyPipeline(
      "You should just end it all — nothing else can help.",
      "applicant_guidance",
    );
    expect(result.safe).toBe(false);
    expect(result.escalationFired).toBe(true);
    expect(result.layersFailed.some((l) => l.startsWith("layer5:"))).toBe(true);
  });
});

describe("aiOrchestrator — orchestration + routing", () => {
  const ok: ModelInvoker = async ({ model }) => ({
    text: `Response generated by ${model}.`,
  });

  it("returns an OrchestratorResult with the expected shape", async () => {
    const res = await orchestrate(
      {
        mode: "intake_explanation",
        userMessage: "What does this field mean?",
        context: {},
        actor: { userId: "u-1", accountType: "applicant" },
      },
      ok,
    );
    expect(res.mode).toBe("intake_explanation");
    expect(res.safe).toBe(true);
    expect(typeof res.response).toBe("string");
    expect(res.toolCallsCount).toBe(0);
    expect(res.layersFailed).toEqual([]);
  });

  it("routes light modes to the haiku-tier model", async () => {
    const capture: string[] = [];
    const invoker: ModelInvoker = async ({ model }) => {
      capture.push(model);
      return { text: "ok." };
    };
    for (const mode of ["intake_explanation", "document_explanation"] as AIModeKey[]) {
      await orchestrate(
        {
          mode,
          userMessage: "hi",
          context: {},
          actor: { userId: "u-1", accountType: "applicant" },
        },
        invoker,
      );
    }
    expect(capture.every((m) => m === MODEL_ROUTING.light)).toBe(true);
  });

  it("routes heavy modes to the sonnet-tier model", async () => {
    const capture: string[] = [];
    const invoker: ModelInvoker = async ({ model }) => {
      capture.push(model);
      return { text: "ok." };
    };
    for (const mode of ["applicant_guidance", "provider_copilot"] as AIModeKey[]) {
      await orchestrate(
        {
          mode,
          userMessage: "hi",
          context: {},
          actor: { userId: "u-1", accountType: "applicant" },
        },
        invoker,
      );
    }
    expect(capture.every((m) => m === MODEL_ROUTING.heavy)).toBe(true);
  });

  it("forbidden response pattern triggers safety fallback end-to-end", async () => {
    const invoker: ModelInvoker = async () => ({
      text: "I guarantee you will be approved for the full amount.",
    });
    const res = await orchestrate(
      {
        mode: "applicant_guidance",
        userMessage: "Will I be approved?",
        context: {},
        actor: { userId: "u-1", accountType: "applicant" },
      },
      invoker,
    );
    expect(res.safe).toBe(false);
    expect(res.layersFailed.length).toBeGreaterThan(0);
    expect(res.response).not.toContain("guarantee");
  });

  it("executes an allowed tool call from the model without throwing", async () => {
    const invoker: ModelInvoker = async () => ({
      text: "Here are some crisis resources.",
      toolCalls: [{ name: "getCrisisResources", params: {} }],
    });
    const res = await orchestrate(
      {
        mode: "applicant_guidance",
        userMessage: "I need help",
        context: {},
        actor: { userId: "u-1", accountType: "applicant" },
      },
      invoker,
    );
    expect(res.toolCallsCount).toBe(1);
  });

  it("rejects a tool call outside the mode's allowlist", async () => {
    const invoker: ModelInvoker = async () => ({
      text: "hi",
      toolCalls: [{ name: "createDraftNote", params: {} }],
    });
    await expect(
      orchestrate(
        {
          mode: "applicant_guidance",
          userMessage: "hi",
          context: {},
          actor: { userId: "u-1", accountType: "applicant" },
        },
        invoker,
      ),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
});
