#!/usr/bin/env node
/**
 * Auto Pipeline 2.0 — commit-and-pr.js
 *
 * Stages all changes, commits with a standard message, pushes the domain
 * branch, and opens a GitHub PR via the gh CLI. The last manual step
 * before human review.
 *
 * Usage:
 *   node scripts/commit-and-pr.js --domain 3.1
 *
 * Reads:
 *   config/domain-pages.json    — slug, name
 *   artifacts/domain-X.Y-validation.json (optional)
 *   artifacts/domain-X.Y-implementation.md (optional, for PR body)
 *
 * Writes:
 *   artifacts/domain-X.Y-pr.txt — the URL of the created PR
 *
 * Requires:
 *   gh CLI installed and authenticated (PATH includes /opt/homebrew/bin)
 *   Current branch must be domain/<slug>
 */

const fs = require("fs");
const path = require("path");
const { execSync, spawnSync } = require("child_process");

// ---------------------------------------------------------------------------
// CLI parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--domain") args.domain = argv[++i];
  }
  return args;
}

const { domain } = parseArgs(process.argv.slice(2));

if (!domain) {
  console.error("Usage: node scripts/commit-and-pr.js --domain X.Y");
  console.error("Example: node scripts/commit-and-pr.js --domain 3.1");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const repoRoot = path.resolve(__dirname, "..");
const artifactsDir = path.join(repoRoot, "artifacts");

// Ensure /opt/homebrew/bin is on PATH so gh is found in non-interactive shells
const env = { ...process.env };
const extraPath = "/opt/homebrew/bin:/usr/local/bin";
env.PATH = env.PATH ? extraPath + ":" + env.PATH : extraPath;

function fail(msg) {
  console.error(`[commit-and-pr] FAILED: ${msg}`);
  process.exit(1);
}

function log(msg) {
  console.log(`[commit-and-pr] ${msg}`);
}

function sh(cmd, opts = {}) {
  return execSync(cmd, { cwd: repoRoot, encoding: "utf8", env, ...opts });
}

// ---------------------------------------------------------------------------
// Load config
// ---------------------------------------------------------------------------

const configPath = path.join(repoRoot, "config", "domain-pages.json");
let domainPages;
try {
  domainPages = JSON.parse(fs.readFileSync(configPath, "utf8"));
} catch (err) {
  fail(`cannot read ${configPath}: ${err.message}`);
}

const config = domainPages[domain];
if (!config) {
  fail(
    `domain '${domain}' not found in domain-pages.json. ` +
      `Available: ${Object.keys(domainPages).join(", ")}`,
  );
}

const branch = `domain/${config.slug}`;

// ---------------------------------------------------------------------------
// Sanity checks: are we on the right branch? gh installed?
// ---------------------------------------------------------------------------

let currentBranch;
try {
  currentBranch = sh("git rev-parse --abbrev-ref HEAD").trim();
} catch (err) {
  fail(`cannot determine current branch: ${err.message}`);
}

if (currentBranch !== branch) {
  fail(
    `current branch is '${currentBranch}' but expected '${branch}'. ` +
      `Run preflight.js first or git checkout ${branch}.`,
  );
}

try {
  sh("gh --version", { stdio: "pipe" });
} catch {
  fail(
    "gh CLI is not available on PATH. Install it (brew install gh) and " +
      "authenticate (gh auth login) before running this script.",
  );
}

// ---------------------------------------------------------------------------
// Stage and report
// ---------------------------------------------------------------------------

log(`Domain ${domain} (${config.name}) — staging changes`);
sh("git add -A");

const status = sh("git status --porcelain").trim();
if (!status) {
  fail("nothing to commit. Did you forget to run the execution step?");
}

log("Changes staged:");
for (const line of status.split("\n")) console.log("  " + line);

// ---------------------------------------------------------------------------
// Commit
// ---------------------------------------------------------------------------

const commitMessage = `domain/${config.slug}: implement ${config.name}\n\nAuto Pipeline 2.0 — commit generated by commit-and-pr.js for domain ${domain}.\n\nCo-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>`;

const commitResult = spawnSync("git", ["commit", "-m", commitMessage], {
  cwd: repoRoot,
  encoding: "utf8",
  env,
});
if (commitResult.status !== 0) {
  fail(
    `git commit failed:\n${(commitResult.stdout || "") + (commitResult.stderr || "")}`,
  );
}
log("Committed.");

// ---------------------------------------------------------------------------
// Push
// ---------------------------------------------------------------------------

log(`Pushing ${branch} to origin...`);
try {
  sh(`git push -u origin ${branch}`);
} catch (err) {
  fail(`git push failed: ${err.message}`);
}

// ---------------------------------------------------------------------------
// PR body — prefer artifact if present, otherwise use a standard template
// ---------------------------------------------------------------------------

const implPath = path.join(artifactsDir, `domain-${domain}-implementation.md`);
const validationPath = path.join(artifactsDir, `domain-${domain}-validation.json`);

let prBody;
if (fs.existsSync(implPath)) {
  prBody = fs.readFileSync(implPath, "utf8");
} else {
  let validationLine = "Validation gates not recorded.";
  if (fs.existsSync(validationPath)) {
    try {
      const v = JSON.parse(fs.readFileSync(validationPath, "utf8"));
      validationLine = `Validation: TSC=0, tests=${v.testCount ?? "?"}, build=ok, all gates passed.`;
    } catch {
      // ignore
    }
  }
  prBody = [
    `## Domain ${domain} — ${config.name}`,
    "",
    `Auto Pipeline 2.0 generated PR. Implementation produced by Claude Code on branch \`${branch}\`.`,
    "",
    "## Validation",
    "",
    validationLine,
    "",
    "## Test plan",
    "",
    "- [ ] Code review",
    "- [ ] CI checks pass (validate, Vercel, Supabase Preview)",
    "- [ ] Notion implementation notes posted to page 5",
    "",
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
  ].join("\n");
}

// Write PR body to a temp file so gh --body-file gets the exact text
const bodyFile = path.join(artifactsDir, `domain-${domain}-pr-body.tmp.md`);
fs.mkdirSync(artifactsDir, { recursive: true });
fs.writeFileSync(bodyFile, prBody);

// ---------------------------------------------------------------------------
// Open PR
// ---------------------------------------------------------------------------

log("Opening GitHub PR...");
const prTitle = `[Domain ${domain}] ${config.name}`;
const prResult = spawnSync(
  "gh",
  [
    "pr",
    "create",
    "--title",
    prTitle,
    "--body-file",
    bodyFile,
    "--base",
    "NXTSTPS2.0-V1",
    "--head",
    branch,
  ],
  { cwd: repoRoot, encoding: "utf8", env },
);

// Clean up temp body file
try {
  fs.unlinkSync(bodyFile);
} catch {
  // ignore
}

if (prResult.status !== 0) {
  fail(
    `gh pr create failed:\n${(prResult.stdout || "") + (prResult.stderr || "")}`,
  );
}

const prOutput = (prResult.stdout || "") + (prResult.stderr || "");
const prUrlMatch = prOutput.match(/https:\/\/github\.com\/[^\s]+/);
const prUrl = prUrlMatch ? prUrlMatch[0].trim() : null;

if (!prUrl) {
  fail(`could not parse PR URL from gh output:\n${prOutput}`);
}

// Persist the URL for downstream scripts (notion-closeout.js consumes this)
const prArtifactPath = path.join(artifactsDir, `domain-${domain}-pr.txt`);
fs.writeFileSync(prArtifactPath, prUrl + "\n");

log(`PR created: ${prUrl}`);
log(`PR URL written to ${prArtifactPath}`);

console.log(JSON.stringify({ success: true, domain, branch, prUrl }));
