-- Phase 10: Seed initial knowledge base entries for Illinois and Indiana compensation programs.
-- Entries are inserted as active so the system is immediately useful.
-- Idempotent: only insert when no row with that entry_key exists.

insert into public.knowledge_entries (
  entry_key,
  title,
  body,
  category,
  state_code,
  program_key,
  workflow_key,
  version,
  status,
  is_active,
  structured_data,
  source_label
) values
(
  'il.vc.program_overview',
  'Illinois Crime Victims Compensation Program – Overview',
  'The Illinois Crime Victims Compensation Program can help pay certain expenses for victims of violent crime and their families. The program is administered by the Illinois Attorney General. Eligible expenses may include medical and counseling costs, lost wages, funeral expenses, and other crime-related losses. You must report the crime to law enforcement and cooperate with the investigation. This is general information, not legal advice.',
  'program_overview',
  'IL',
  'illinois_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"eligibility_factors": ["reported_to_police", "cooperation_expected"], "notes": ["Administered by IL Attorney General"]}'::jsonb,
  'Illinois Attorney General – Crime Victims Compensation'
),
(
  'il.vc.eligibility.overview',
  'Illinois – Who May Qualify',
  'Generally, you may apply if you are a victim of a violent crime that occurred in Illinois, or a family member or person who paid for the victim''s expenses. The crime must have been reported to law enforcement within a reasonable time. Applicants are expected to cooperate with law enforcement and the Attorney General''s office. Certain deadlines and eligibility rules apply. This is general information, not legal advice.',
  'eligibility',
  'IL',
  'illinois_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"eligibility_factors": ["reported_to_police", "cooperation_expected", "violent_crime_in_il"], "deadline_days": 365}'::jsonb,
  'Illinois Crime Victims Compensation'
),
(
  'il.vc.documents.overview',
  'Illinois – Common Required Documents',
  'Common documents requested include: police report or case number, medical or counseling bills, proof of lost wages, funeral or burial invoices if applicable, and identification. The Attorney General may request additional documents depending on the type of claim. Keep copies of everything you submit. This is general information, not legal advice.',
  'documents',
  'IL',
  'illinois_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"required_documents": ["police_report", "medical_bill", "proof_of_identity", "funeral_invoice_if_applicable"]}'::jsonb,
  'Illinois Crime Victims Compensation'
),
(
  'il.vc.timeline.overview',
  'Illinois – Timeline and Deadlines',
  'You generally must apply within a certain time after the crime (often within one to two years; exact rules vary). After you apply, the office may request more information. Processing times vary. Do not wait until the last minute to gather documents. This is general information, not legal advice.',
  'timeline',
  'IL',
  'illinois_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"deadline_days": 730, "notes": ["Processing times vary; submit as soon as possible"]}'::jsonb,
  'Illinois Crime Victims Compensation'
),
(
  'il.vc.definitions.subrogation',
  'What is subrogation?',
  'Subrogation means that if you receive compensation from the state, the state may have the right to recover money from the person who harmed you or from other sources (such as insurance) to the extent they pay for the same losses. Signing an acknowledgment of subrogation is required by the program and does not mean you give up your own rights to seek other compensation; it allows the state to pursue recovery in certain situations. This is general information, not legal advice.',
  'definitions',
  'IL',
  'illinois_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{}'::jsonb,
  'Illinois Crime Victims Compensation'
),
(
  'in.vc.program_overview',
  'Indiana Crime Victims Compensation – Overview',
  'The Indiana Criminal Justice Institute administers the state''s crime victims compensation program. It may help with medical expenses, counseling, lost wages, funeral costs, and other eligible losses for victims of violent crime. You must report the crime and cooperate with law enforcement and the program. This is general information, not legal advice.',
  'program_overview',
  'IN',
  'indiana_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"eligibility_factors": ["reported_to_police", "cooperation_expected"]}'::jsonb,
  'Indiana Criminal Justice Institute'
),
(
  'in.vc.eligibility.overview',
  'Indiana – Who May Qualify',
  'Eligibility generally requires that the crime was reported to law enforcement and that you cooperate with the investigation and with the program. The crime must meet Indiana''s definition of a compensable crime. There are deadlines for applying. This is general information, not legal advice.',
  'eligibility',
  'IN',
  'indiana_vc',
  'compensation_intake',
  '1',
  'active',
  true,
  '{"eligibility_factors": ["reported_to_police", "cooperation_expected"]}'::jsonb,
  'Indiana Crime Victims Compensation'
),
(
  'general.definitions.cooperation',
  'Cooperation with law enforcement',
  'Many compensation programs expect you to cooperate with law enforcement and with the program''s own investigation. This usually means providing information and documents when requested, and not refusing to assist without good reason. If you have concerns about safety or privacy, you can ask the program or an advocate about your options. This is general information, not legal advice.',
  'definitions',
  null,
  null,
  'compensation_intake',
  '1',
  'active',
  true,
  '{}'::jsonb,
  null
);
